const ALL_REQUEST_PROCCESS = 'ALL_REQUEST_PROCCESS';
const ALL_REQUEST_SUCCESS = 'ALL_REQUEST_SUCCESS';
const ALL_REQUEST_ERROR = 'ALL_REQUEST_ERROR';
const ALL_CLEAR_REQUEST = 'ALL_CLEAR_REQUEST';

export {
    ALL_REQUEST_PROCCESS,
    ALL_REQUEST_SUCCESS,
    ALL_REQUEST_ERROR,
    ALL_CLEAR_REQUEST
    
}